"""data types changed for few columns in contents table

Revision ID: 3d606495723a
Revises: 47c6a0c0a9a8
Create Date: 2024-11-26 20:39:26.250836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d606495723a'
down_revision = '47c6a0c0a9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('encryption_key', existing_type=sa.VARCHAR(length=100), type_=sa.LargeBinary(length=256),
                              existing_nullable=False, postgresql_using='encrypted_payload::bytea')
        batch_op.alter_column('encrypted_payload', existing_type=sa.VARCHAR(length=10000), type_=sa.LargeBinary(),
                              existing_nullable=False, postgresql_using='encryption_key::bytea')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('encrypted_payload', existing_type=sa.LargeBinary(), type_=sa.VARCHAR(length=10000),
                              existing_nullable=False, postgresql_using='encrypted_payload::VARCHAR(10000)')
        batch_op.alter_column('encryption_key', existing_type=sa.LargeBinary(length=256), type_=sa.VARCHAR(length=100),
                              existing_nullable=False, postgresql_using='encryption_key::VARCHAR(100)')

    # ### end Alembic commands ###
