"""Initial migration.

Revision ID: ab0d8e4502a9
Revises: 
Create Date: 2024-11-26 14:39:00.598867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0d8e4502a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protection_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('encryption_mode', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protection_system', sa.Integer(), nullable=False),
    sa.Column('encryption_key', sa.String(length=100), nullable=True),
    sa.Column('encrypted_payload', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['protection_system'], ['protection_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('protection_system', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['protection_system'], ['protection_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('content')
    op.drop_table('protection_system')
    # ### end Alembic commands ###
