"""added JSON type feild to store encrypted content.

Revision ID: df399803bb35
Revises: 3d606495723a
Create Date: 2024-11-26 22:10:50.760886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df399803bb35'
down_revision = '3d606495723a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_json', sa.JSON(), nullable=False))
        batch_op.drop_column('encrypted_payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_payload', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('encrypted_json')

    # ### end Alembic commands ###
